#!/bin/sh

# Copyright (C) 2006-2008, 2010, 2012 Free Software Foundation, Inc.
#
# Author: Simon Josefsson
#
# This file is part of GnuTLS.
#
# GnuTLS is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.
#
# GnuTLS is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuTLS; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

#set -e

srcdir="${srcdir:-.}"
CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
DIFF="${DIFF:-diff -b -B}"

if ! test -x "${CERTTOOL}"; then
	exit 77
fi

if ! test -z "${VALGRIND}"; then
	VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
fi

TMPFILE=tmp-$$.pem.tmp
TMPFILE1=tmp1-$$.pem.tmp
TMPFILE2=tmp2-$$.pem.tmp

#check whether "funny" spaces can be interpreted
${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/data/funny-spacing.pem" >/dev/null 2>&1
rc=$?

# We're done.
if test "${rc}" != "0"; then
	echo "Funny-spacing cert decoding failed 1"
	exit ${rc}
fi

#check whether a BMPString attribute can be properly decoded
${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/data/bmpstring.pem" >${TMPFILE}
rc=$?

if test "${rc}" != "0"; then
	echo "BMPString cert decoding failed 1"
	exit ${rc}
fi

#FIXME: the output string differs in windows and linux on the last char.
${DIFF} -I 'Algorithm Security Level' "${srcdir}/data/bmpstring.pem" ${TMPFILE} || ${DIFF} -I 'Algorithm Security Level' --strip-trailing-cr "${srcdir}/data/bmpstring.pem" ${TMPFILE}
rc=$?

if test "${rc}" != "0"; then
	echo "BMPString cert decoding failed 2"
	exit ${rc}
fi

#check whether complex-cert is decoded as expected
${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/data/complex-cert.pem" >${TMPFILE}
rc=$?

if test "${rc}" != "0"; then
	echo "Complex cert decoding failed 1"
	exit ${rc}
fi

cat "${srcdir}/data/complex-cert.pem" |grep -v "Not After:" >${TMPFILE1}
cat ${TMPFILE} |grep -v "Not After:" >${TMPFILE2}
${DIFF} -I 'Algorithm Security Level' ${TMPFILE1} ${TMPFILE2} || ${DIFF} -I 'Algorithm Security Level' --strip-trailing-cr ${TMPFILE1} ${TMPFILE2}
rc=$?

if test "${rc}" != "0"; then
	echo "Complex cert decoding failed 2"
	exit ${rc}
fi

#check whether the cert with many othernames is decoded as expected
${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/data/xmpp-othername.pem" >${TMPFILE}
rc=$?

if test "${rc}" != "0"; then
	echo "XMPP cert decoding failed 1"
	exit ${rc}
fi

cat "${srcdir}/data/xmpp-othername.pem" |grep -v "Not After:" >${TMPFILE1}
cat ${TMPFILE} |grep -v "Not After:" >${TMPFILE2}
${DIFF} -I 'Algorithm Security Level' ${TMPFILE1} ${TMPFILE2} || ${DIFF} -I 'Algorithm Security Level' --strip-trailing-cr ${TMPFILE1} ${TMPFILE2}
rc=$?

if test "${rc}" != "0"; then
	echo "XMPP cert decoding failed 2"
	exit ${rc}
fi

${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/data/template-krb5name.pem" >${TMPFILE}
rc=$?

if test "${rc}" != "0"; then
	echo "XMPP cert decoding failed 1"
	exit ${rc}
fi

cat ${TMPFILE} |grep "KRB5Principal:" >${TMPFILE1}
cat "${srcdir}/data/template-krb5name-full.pem" |grep "KRB5Principal:" >${TMPFILE2}
${DIFF} -I 'Algorithm Security Level' -u ${TMPFILE1} ${TMPFILE2} || ${DIFF} -I 'Algorithm Security Level' -u --strip-trailing-cr ${TMPFILE1} ${TMPFILE2}
rc=$?

if test "${rc}" != "0"; then
	echo "KRB5 principalname cert decoding failed 1"
	exit ${rc}
fi


#check whether the cert with GOST parameters is decoded as expected
${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/data/gost-cert.pem" >${TMPFILE}
rc=$?

if test "${rc}" != "0"; then
	echo "GOST cert decoding failed 1"
	exit ${rc}
fi

${DIFF} -I 'Algorithm Security Level' ${TMPFILE} "${srcdir}/data/gost-cert.pem" || ${DIFF} -I 'Algorithm Security Level' --strip-trailing-cr "${TMPFILE}" "${srcdir}/data/gost-cert.pem"
rc=$?

if test "${rc}" != "0"; then
	echo "GOST cert decoding failed 2"
	exit ${rc}
fi

${VALGRIND} "${CERTTOOL}" --certificate-info --infile "${srcdir}/data/multi-value-dn.pem" >${TMPFILE}
rc=$?

if test "${rc}" != "0"; then
	echo "MV-DN cert decoding failed 1"
	exit ${rc}
fi

${DIFF} -I 'Algorithm Security Level' ${TMPFILE} "${srcdir}/data/multi-value-dn.pem" || ${DIFF} -I 'Algorithm Security Level' --strip-trailing-cr "${TMPFILE}" "${srcdir}/data/multi-value-dn.pem"
rc=$?

if test "${rc}" != "0"; then
	echo "MV-DN cert decoding failed 2"
	exit ${rc}
fi

rm -f ${TMPFILE} ${TMPFILE1} ${TMPFILE2}

exit 0
