#!/bin/sh

# Copyright (C) 2006-2012 Free Software Foundation, Inc.
#
# This file is part of GnuTLS.
#
# GnuTLS is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.
#
# GnuTLS is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuTLS; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

#set -e

srcdir="${srcdir:-.}"
ac_cv_sizeof_unsigned_long_int="${ac_cv_sizeof_unsigned_long_int:-8}"
CERTTOOL="${CERTTOOL:-../../src/certtool${EXEEXT}}"
DIFF="${DIFF:-diff}"

if ! test -x "${CERTTOOL}"; then
	exit 77
fi

export TZ="UTC"

. ${srcdir}/../scripts/common.sh

check_for_datefudge

# Note that in rare cases this test may fail because the
# time set using datefudge could have changed since the generation
# (if example the system was busy)

datefudge -s "2007-04-22" \
	"${CERTTOOL}" --generate-self-signed \
		--load-privkey "${srcdir}/data/template-test.key" \
		--template "${srcdir}/templates/template-test.tmpl" \
		--outfile tmp-tt.pem 2>/dev/null

${DIFF} "${srcdir}/data/template-test.pem" tmp-tt.pem >/dev/null 2>&1
rc=$?

# We're done.
if test "${rc}" != "0"; then
	echo "Test 1 failed"
	exit ${rc}
fi

rm -f tmp-tt.pem

datefudge -s "2007-04-22" \
	"${CERTTOOL}" --generate-self-signed \
		--load-privkey "${srcdir}/data/template-test.key" \
		--template "${srcdir}/templates/template-utf8.tmpl" \
		--outfile tmp-tt.pem 2>/dev/null

${DIFF} "${srcdir}/data/template-utf8.pem" tmp-tt.pem >/dev/null 2>&1
rc=$?

# We're done.
if test "${rc}" != "0"; then
	echo "Test 2 (UTF8) failed"
	exit ${rc}
fi

rm -f tmp-tt.pem

datefudge -s "2007-04-22" \
	"${CERTTOOL}" --generate-self-signed \
		--load-privkey "${srcdir}/data/template-test.key" \
		--template "${srcdir}/templates/template-dn.tmpl" \
		--outfile tmp-tt.pem 2>/dev/null

${DIFF} "${srcdir}/data/template-dn.pem" tmp-tt.pem >/dev/null 2>&1
rc=$?

# We're done.
if test "${rc}" != "0"; then
	echo "Test 3 (DN) failed"
	exit ${rc}
fi

rm -f tmp-tt.pem

datefudge -s "2007-04-22" \
	"${CERTTOOL}" --generate-self-signed \
		--load-privkey "${srcdir}/data/template-test.key" \
		--template "${srcdir}/templates/template-dn-err.tmpl" \
		--outfile tmp-tt.pem 2>/dev/null
rc=$?

if test "${rc}" = "0"; then
	echo "Test 3 (DN-err) failed"
	exit ${rc}
fi

rm -f tmp-tt.pem

datefudge -s "2007-04-22" \
	"${CERTTOOL}" --generate-self-signed \
		--load-privkey "${srcdir}/data/template-test.key" \
		--template "${srcdir}/templates/template-overflow.tmpl" \
		--outfile tmp-tt.pem 2>/dev/null

${DIFF} "${srcdir}/data/template-overflow.pem" tmp-tt.pem >/dev/null 2>&1
rc=$?

# We're done.
if test "${rc}" != "0"; then
	echo "Test 4 (overflow1) failed"
	exit ${rc}
fi

rm -f tmp-tt.pem

# The following test works in 64-bit systems
if test "${ac_cv_sizeof_unsigned_long_int}" = 8;then

datefudge -s "2007-04-22" \
	"${CERTTOOL}" --generate-self-signed \
		--load-privkey "${srcdir}/data/template-test.key" \
		--template "${srcdir}/templates/template-overflow2.tmpl" \
		--outfile tmp-tt.pem 2>/dev/null

${DIFF} "${srcdir}/data/template-overflow2.pem" tmp-tt.pem >/dev/null 2>&1
rc=$?

# We're done.
if test "${rc}" != "0"; then
	echo "Test 5 (overflow2) failed"
	exit ${rc}
fi

rm -f tmp-tt.pem
fi

datefudge -s "2007-04-22" \
	"${CERTTOOL}" --generate-self-signed \
		--load-privkey "${srcdir}/data/template-test.key" \
		--template "${srcdir}/templates/template-date.tmpl" \
		--outfile tmp-tt.pem 2>/dev/null

${DIFF} "${srcdir}/data/template-date.pem" tmp-tt.pem >/dev/null 2>&1
rc=$?

# We're done.
if test "${rc}" != "0"; then
	echo "Test 6 (explicit dates) failed"
	exit ${rc}
fi

rm -f tmp-tt.pem

# Test name constraints generation

datefudge -s "2007-04-22" \
	"${CERTTOOL}" --generate-self-signed \
		--load-privkey "${srcdir}/data/template-test.key" \
		--template "${srcdir}/templates/template-nc.tmpl" \
		--outfile tmp-tt.pem 2>/dev/null

${DIFF} "${srcdir}/data/template-nc.pem" tmp-tt.pem >/dev/null 2>&1
rc=$?

# We're done.
if test "${rc}" != "0"; then
	echo "Test 7 (name constraints) failed"
	exit ${rc}
fi

rm -f tmp-tt.pem


# Test the GeneralizedTime support
if test "${ac_cv_sizeof_unsigned_long_int}" = 8;then
	# we should test that on systems which have 64-bit time_t.
	datefudge -s "2051-04-22" \
			"${CERTTOOL}" --generate-self-signed \
				--load-privkey "${srcdir}/data/template-test.key" \
				--template "${srcdir}/templates/template-generalized.tmpl" \
				--outfile tmp-tt.pem 2>/dev/null

	${DIFF} "${srcdir}/data/template-generalized.pem" tmp-tt.pem >/dev/null 2>&1
	rc=$?

	# We're done.
	if test "${rc}" != "0"; then
		echo "Test 8 (generalizedTime) failed"
		exit ${rc}
	fi
fi

rm -f tmp-tt.pem

# Test unique ID field generation

datefudge -s "2007-04-22" \
	"${CERTTOOL}" --generate-self-signed \
		--load-privkey "${srcdir}/data/template-test.key" \
		--template "${srcdir}/templates/template-unique.tmpl" \
		--outfile tmp-tt.pem 2>/dev/null

${DIFF} "${srcdir}/data/template-unique.pem" tmp-tt.pem >/dev/null 2>&1
rc=$?

# We're done.
if test "${rc}" != "0"; then
	echo "Test 9 (unique ID) failed"
	exit ${rc}
fi

rm -f tmp-tt.pem

exit 0
