#! /bin/sh

../../src/gnutls-serv --http --x509certfile x509/cert-rsa.pem --x509keyfile x509/key-rsa.pem --x509cafile x509/ca.pem \
	--x509certfile x509/cert-dsa.pem --x509keyfile x509/key-dsa.pem	\
	--x509certfile x509/cert-ecc.pem --x509keyfile x509/key-ecc.pem	\
	--x509certfile x509/cert-rsa-pss.pem --x509keyfile x509/key-rsa-pss.pem	\
	--x509certfile x509/cert-gost01.pem --x509keyfile x509/key-gost01.pem \
	--srppasswd srp/tpasswd --srppasswdconf srp/tpasswd.conf \
	--pskpasswd psk-passwd.txt \
	$*
