#! /bin/sh

../../src/gnutls-serv --http --x509certfile x509/cert-rsa.pem --x509keyfile x509/key-rsa.pem --x509cafile x509/ca.pem \
	--x509dsacertfile x509/cert-dsa.pem --x509dsakeyfile x509/key-dsa.pem	\
	--x509ecccertfile x509/cert-ecc.pem --x509ecckeyfile x509/key-ecc.pem	\
	--srppasswd srp/tpasswd --srppasswdconf srp/tpasswd.conf \
	--pgpkeyfile openpgp/sec.asc --pgpcertfile openpgp/pub.asc --pskpasswd psk-passwd.txt \
	$*
